#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install  -y --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get install haproxy=2.6.\*

echo "ENABLED=1" >> /etc/default/haproxy

# Listen to web1 and web2 servers
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 107444-web-01 100.25.169.174:80 check
   server 107444-web-02 34.229.69.57:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
