#!/usr/bin/env bash
# This script displays Best School 10 time 
# But for the 9th iteration, displays "Best School" and then "Hi" on a new line.

i=10
while (( i>0 ))
do
	echo "Best School"
        if (( i == 2 ))
	then
		echo "Hi"
	fi
	(( i-- ))

done
