#!/usr/bin/env bash
# Loops from 1 to 10
# displays "bad luck" for the 4th loop
# displays "good luck" for the 8th loop
# displays "Best School" for the rest

i=10
while (( i>0 ))
do
	if (( i == 7 ))
	then
		echo "bad luck"
	elif (( i == 3 ))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i-- ))

done
