#!/usr/bin/env bash
# Loops from 1 to 20
# displays "bad luck from China" for the 4th loop
# displays "bad luck from Japan" for the 9th loop
# displays "bad luck from Italy" for the 17th loop
# displays the number for the rest

i=1
while (( i<21 ))
do
	echo $i
	if (( i == 4 ))
	then
		echo "bad luck from China"
	elif (( i == 9 ))
	then
		echo "bad luck from Japan"
	elif (( i == 17 ))
	then
		echo "bad luck from Italy"
	fi
	(( i++ ))

done
