#!/usr/bin/env bash
# Loops from 1 to 20
# displays "bad luck from China" for the 4th loop
# displays "bad luck from Japan" for the 9th loop
# displays "bad luck from Italy" for the 17th loop
# displays the number for the rest

i=1
while (( i<21 ))
do
	echo $i
	case $count in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( i++ ))

done
